# Generated by Django 4.0.5 on 2022-07-17 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_soft_desk', '0002_issues_contributors_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributors',
            name='role',
            field=models.CharField(choices=[('auteur', 'auteur'), ('contributeur', 'contributeur')], max_length=150),
        ),
    ]
