# Generated by Django 4.0.5 on 2022-07-27 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API_soft_desk', '0007_projects_contributor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='contributor',
        ),
    ]
