# Generated by Django 4.0.5 on 2022-07-27 11:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("API_soft_desk", "0008_remove_projects_contributor"),
    ]

    operations = [
        migrations.AddField(
            model_name="projects",
            name="contributor",
            field=models.ManyToManyField(
                related_name="contributions",
                through="API_soft_desk.Contributors",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
