# Generated by Django 4.0.5 on 2022-07-28 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_soft_desk', '0009_projects_contributor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributors',
            name='permission',
            field=models.CharField(choices=[('lecture_seule', 'lecture_seule'), ('total', 'total')], max_length=13),
        ),
    ]
