# Generated by Django 4.0.5 on 2022-08-10 15:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("API_soft_desk", "0021_alter_issues_created_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issues",
            name="created_time",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
