# Generated by Django 4.0.5 on 2022-08-10 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("API_soft_desk", "0022_alter_issues_created_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issues",
            name="created_time",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
